# Wstęp

In [4]:
import pandas as pd, numpy as np
frame = pd.read_csv('http://piotrdomagala.pl/data/Mcdonalds.csv')

In [7]:
frame.loc[1,'Calories']= np.NaN
frame.loc[2,'TotalFat'] = np.NaN

frame.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),NaN,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370.0,200,NaN,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [8]:
frame.dropna().head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460.0,230,26.0,40,13.0,65,0.0,...,38,13,2,7,3,19,10,8,15,15

In [9]:
# how=any - usuwa z ramki wszystkie wiersze, gdzie chociaż jedno pole jest puste (wartośc domyślna)
# how=all - usuwa z ramki wszystkie wiersze, gdzie wszystkie pola są puste

frame.dropna(how="all").head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),NaN,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370.0,200,NaN,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [11]:
# subset określa zakres w jakim wartości nie mogą być puste i usuwa wiersze z wartościami pustymi we wskazanych kolumnach
frame.dropna(subset=['TotalFat'], how='any').head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),NaN,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20

In [12]:
# axis określa czy bierzemy pod uwagę wierszy czy kolumny
# axis='columns' (1) usuwa kolumny w których znalezione zostaly puste wartości
# axis='rows' (0) usuwa wiersze, w których znalezione zostaly puste wartości
frame.dropna(axis='rows').head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460.0,230,26.0,40,13.0,65,0.0,...,38,13,2,7,3,19,10,8,15,15

In [13]:
# inplace - usuwamy wartości na oryginalnej ramce danych
frame.dropna(inplace=True)
frame

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300.0,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450.0,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400.0,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430.0,210,23.0,36,9.0,46,1.0,...,31,10,4,18,3,26,15,2,30,20
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460.0,230,26.0,40,13.0,65,0.0,...,38,13,2,7,3,19,10,8,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Smoothies & Shakes,McFlurry with Oreo Cookies (Small),10.1 oz (285 g),510.0,150,17.0,26,9.0,44,0.5,...,80,27,1,4,64,12,15,0,40,8
256,Smoothies & Shakes,McFlurry with Oreo Cookies (Medium),13.4 oz (381 g),690.0,200,23.0,35,12.0,58,1.0,...,106,35,1,5,85,15,20,0,50,10
257,Smoothies & Shakes,McFlurry with Oreo Cookies (Snack),6.7 oz (190 g),340.0,100,11.0,17,6.0,29,0.0,...,53,18,1,2,43,8,10,0,25,6
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),14.2 oz (403 g),810.0,290,32.0,50,15.0,76,1.0,...,114,38,2,9,103,21,20,0,60,6
259,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Snack),7.1 oz (202 g),410.0,150,16.0,25,8.0,38,0.0,...,57,19,1,5,51,10,10,0,30,4

# Zadanie

In [15]:
import pandas as pd, numpy as np
fuel = pd.read_csv('http://piotrdomagala.pl/data/fuel.csv',
                   low_memory=False,
                   usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type', 'Combined MPG (FT1)'],
                   index_col='Vehicle ID'
                   )

In [16]:
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0

In [17]:
fuel.loc[27705, 'Class'] = np.NaN
fuel.loc[26561, 'Class'] = np.NaN
fuel.loc[27550, 'Fuel Type'] = np.NaN

In [18]:
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,NaN,Regular,20.0
26561,1984,Alfa Romeo,Spider Veloce 2000,NaN,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,NaN,17.0

In [19]:
fuel.dropna().head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0
27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Regular,13.0
28425,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Regular,13.0

In [20]:
fuel.dropna(axis='columns', how='any').head()

,Year,Make
Vehicle ID,,
26587,1984,Alfa Romeo
27705,1984,Alfa Romeo
26561,1984,Alfa Romeo
27681,1984,Alfa Romeo
27550,1984,AM General

In [21]:
fuel.dropna(subset=['Class'], how='any').head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,NaN,17.0
28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0
27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Regular,13.0

In [22]:
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,NaN,Regular,20.0
26561,1984,Alfa Romeo,Spider Veloce 2000,NaN,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,NaN,17.0

In [26]:
fuel.dropna(subset=['Class'], inplace=True)
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,NaN,17.0
28426,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0
27549,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Regular,13.0