# Wstęp

In [1]:
import pandas as pd, numpy as np
frame = pd.read_csv('http://piotrdomagala.pl/data/Mcdonalds.csv')

In [2]:
frame.loc[1,'TotalFat'] = np.NaN
frame.loc[1,'Saturated Fat'] = np.NaN
frame.loc[2,'Saturated Fat'] = np.NaN
frame.loc[3,'Category'] = np.NaN

In [3]:
frame.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,NaN,12,NaN,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,NaN,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,NaN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [4]:
frame.fillna(value=0).head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,0.0,12,0.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,0.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,0,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [5]:
# możemy przypisać wartości do podmiany dla każdej kolumny osobno

replaceDefinitionTable = {'Category':'UNKNOWN', 'TotalFat':0,'SaturatedFat':0}
frame.fillna(value=replaceDefinitionTable).head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,0.0,12,NaN,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,NaN,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,UNKNOWN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [6]:
# wypełniamy puste wartości dla konkretnej kolumny

frame['Category'].fillna(value='UNKNOWN', inplace=True)
frame.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,NaN,12,NaN,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,NaN,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,UNKNOWN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [7]:
frame['Saturated Fat'].fillna(value=0, inplace=True)
frame.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,NaN,12,0.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,0.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,UNKNOWN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [8]:
frame['TotalFat'].fillna(value=0, inplace=True)
frame.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,0.0,12,0.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,0.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,UNKNOWN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [9]:
frame.loc[1,'TotalFat'] = np.NaN
frame.loc[1,'Saturated Fat'] = np.NaN
frame.loc[2,'Saturated Fat'] = np.NaN
frame.loc[3,'Category'] = np.NaN

In [10]:
frame.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,NaN,12,NaN,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,NaN,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,NaN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [11]:
avgTotalFat = frame['TotalFat'].mean()
avgTotalFat

14.18918918918919

In [12]:
frame['TotalFat'].fillna(avgTotalFat, inplace=True)
frame.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.000000,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,14.189189,12,NaN,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.000000,35,NaN,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,NaN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.000000,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.000000,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

In [13]:
frame['Saturated Fat'].fillna(method='ffill', inplace=True)
frame.head()

,Category,Item,Serving Size,Calories,Calories from Fat,TotalFat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.000000,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,14.189189,12,5.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.000000,35,5.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,NaN,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.000000,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.000000,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

# Zadanie

In [14]:
import pandas as pd, numpy as np
fuel = pd.read_csv('http://piotrdomagala.pl/data/fuel.csv',
                   low_memory=False,
                   usecols=['Vehicle ID','Year','Make','Model','Class','Fuel Type', 'Combined MPG (FT1)'],
                   index_col='Vehicle ID'
                   )

In [16]:
fuel.loc[27705, 'Class'] = np.NaN
fuel.loc[26561, 'Class'] = np.NaN
fuel.loc[27550, 'Fuel Type'] = np.NaN
fuel.loc[27705, 'Combined MPG (FT1)'] = np.NaN
fuel.loc[27681, 'Combined MPG (FT1)'] = np.NaN

fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,NaN,Regular,NaN
26561,1984,Alfa Romeo,Spider Veloce 2000,NaN,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,NaN
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,NaN,17.0

In [17]:
fuel.fillna(value=-1).head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,-1,Regular,-1.0
26561,1984,Alfa Romeo,Spider Veloce 2000,-1,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,-1.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,-1,17.0

In [18]:
replaceRules = {'Class':'---', 'Fuel Type':'---', 'Combined MPG (FT1)':-1}
fuel.fillna(value=replaceRules).head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,---,Regular,-1.0
26561,1984,Alfa Romeo,Spider Veloce 2000,---,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,-1.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,---,17.0

In [19]:
avgMPG = fuel['Combined MPG (FT1)'].mean()
avgMPG

19.444177898424922

In [20]:
fuel['Class'].fillna(value='?', inplace=True)
fuel['Fuel Type'].fillna(value='?', inplace=True)
fuel['Combined MPG (FT1)'].fillna(value=-1, inplace=True)

fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,?,Regular,-1.0
26561,1984,Alfa Romeo,Spider Veloce 2000,?,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,-1.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,?,17.0

In [21]:
fuel.loc[27705, 'Class'] = np.NaN
fuel.loc[26561, 'Class'] = np.NaN
fuel.loc[27550, 'Fuel Type'] = np.NaN
fuel.loc[27705, 'Combined MPG (FT1)'] = np.NaN
fuel.loc[27681, 'Combined MPG (FT1)'] = np.NaN

fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,NaN,Regular,NaN
26561,1984,Alfa Romeo,Spider Veloce 2000,NaN,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,NaN
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,NaN,17.0

In [22]:
fuel['Combined MPG (FT1)'].fillna(method='ffill', inplace=True)
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,NaN,Regular,20.0
26561,1984,Alfa Romeo,Spider Veloce 2000,NaN,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,NaN,17.0